// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using studentApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace studentApi.Models
{
    public partial interface IStudentContextProcedures
    {
        Task<List<GetStudentDetailResult>> GetStudentDetailAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
