// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using studentApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace studentApi.Models
{
    public partial class StudentContext
    {
        private IStudentContextProcedures _procedures;

        public virtual IStudentContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new StudentContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IStudentContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetStudentDetailResult>().HasNoKey().ToView(null);
        }
    }

    public partial class StudentContextProcedures : IStudentContextProcedures
    {
        private readonly StudentContext _context;

        public StudentContextProcedures(StudentContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetStudentDetailResult>> GetStudentDetailAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetStudentDetailResult>("EXEC @returnValue = [dbo].[GetStudentDetail]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
